import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google"
import localFont from 'next/font/local'
import "./globals.css";

export const century = localFont({ src: '../../public/fonts/centurygothic_bold.ttf' })

export const noto = Noto_Sans({
  subsets: ["latin", 'cyrillic'],
  weight: ['300', '400', '500', '700'],
  variable: "--font-noto",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className}`}>{children}</body>
    </html>
  );
}
